/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#002f51',
        'primary-container': '#064673',
        'on-primary': '#ffffff',
        'on-primary-container': '#85b4e8',
        'primary-fixed': '#d0e4ff',
        'primary-fixed-dim': '#9bcaff',
        secondary: '#20609f',
        'secondary-container': '#83b9fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#004981',
        'secondary-fixed': '#d2e4ff',
        surface: '#faf9f9',
        'surface-muted': '#F4F7F9',
        'surface-dim': '#dadada',
        'surface-container': '#eeeeee',
        'surface-container-low': '#f4f3f3',
        'surface-container-high': '#e8e8e8',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#42474f',
        'border-subtle': '#E1E8ED',
        'outline': '#727780',
        'outline-variant': '#c2c7d0',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'status-critical': '#D32F2F',
        'status-warning': '#F57C00',
        'status-optimal': '#388E3C',
        'inverse-surface': '#2f3131',
        'on-primary-fixed': '#001d35',
        'on-primary-fixed-variant': '#0e4977',
        'tertiary': '#203300',
        'on-tertiary-container': '#91bf46',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'display': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.02em' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', fontWeight: '700', letterSpacing: '0.05em' }],
        'tabular-nums': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      width: {
        sidebar: '260px',
      },
      marginLeft: {
        sidebar: '260px',
      },
      spacing: {
        sidebar: '260px',
      }
    },
  },
  plugins: [],
};
